a=int(input("enter first number:\n"))
b=int(input("enter second number:\n"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Floor Division:",a//b)
print("Modulus:",a%b)
print("Exponentiation:",a**b)

